[package]
name = "rectify-uninstaller-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
registry = "1.2.3"
utfx = "0.1.0"
windows-sys = { version = "0.48.0", features = ["Win32_Foundation", "Win32_Security_Cryptography"]}

[build-dependencies]
winres = "0.1.12"