name: Rectify11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["Submodules Sync"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: rectify-uninstaller
          path: target\release\rectify-uninstaller-rs.exe
